FORMAT: 1A
HOST: http://localhost:8080

# Apig/_example API

<!-- include(profile.apib) -->
<!-- include(email.apib) -->
<!-- include(company.apib) -->
<!-- include(job.apib) -->
<!-- include(user.apib) -->
