FORMAT: 1A
HOST: http://localhost:8080

# _example API

<!-- include(email.apib) -->
<!-- include(job.apib) -->
<!-- include(profile.apib) -->
<!-- include(user.apib) -->
<!-- include(company.apib) -->
