# Group Profiles
Welcome to the profiles API. This API provides access to the profiles service.

## profiles [/profiles]

### Create profile [POST]

Create a new profile

+ Request profile (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.wantedly+json
    + Attributes

        + user_id: 1 (number)
        + user ()
        + birthday ()
        + engaged: false (boolean)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (profiles, fixed)

### Get profiles [GET]

Returns profile list.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.wantedly+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array, fixed)
        + (profiles)

## profile details [/profiles/{id}]

+ Parameters
    + id: `1` (enum[string]) - The ID of the desired profile.
        + Members
            + `1`
            + `2`
            + `3`

### Get profile [GET]

Returns profile.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.wantedly+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (profiles, fixed)

### Update profile [PUT]

Update profile.

+ Request profile (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.wantedly+json
    + Attributes

        + user_id: 1 (number)
        + user ()
        + birthday ()
        + engaged: false (boolean)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (profiles, fixed)

### Delete profile [DELETE]

Delete profile.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.wantedly+json

+ Response 204

# Data Structures
## profiles (object)

+ id: 1 (number)
+ user_id: 1 (number)
+ user ()
+ birthday ()
+ engaged: false (boolean)
